name: Security and Code Quality Scan

on:
  pull_request:
    branches:
      - main
      - dev*

jobs:
  scan-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install TruffleHog v3
      - name: Install TruffleHog
        run: |
          echo "📥 Installing TruffleHog..."
          curl -sL https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog_$(uname -s)_$(uname -m) \
            -o trufflehog
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/

      # Run TruffleHog scan
      - name: Run TruffleHog Scan
        run: |
          echo "🔍 Running TruffleHog scan..."
          trufflehog filesystem --directory . --fail

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      # Run Python Linter
      - name: Run flake8 (Linting)
        run: |
          echo "🔎 Running lint checks..."
          flake8 . --select=E

      # Run Python Tests
      - name: Run pytest
        run: |
          echo "🧪 Running tests..."
          pytest --maxfail=1 --disable-warnings -q || [ $? -eq 5 ]
