name: PR Secret Scan (TruffleHog)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write   # needed to post comments

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for commit range

      - name: Run TruffleHog scan
        id: scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            -w /repo \
            trufflesecurity/trufflehog:latest \
            git \
              --only-verified \
              --since-commit "${{ github.event.pull_request.base.sha }}" \
              file:///repo \
            > trufflehog-results.txt || true

          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload TruffleHog results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.txt

      - name: Comment results on PR
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: trufflehog-scan
          path: trufflehog-results.txt

      - name: Fail if secrets found
        run: |
          if grep
