name: PR Secret Scan (TruffleHog)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for PR range)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan PR commits with TruffleHog (Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            -w /repo \
            trufflesecurity/trufflehog:latest \
            git \
              --only-verified \
              --fail \
              --since-commit "${{ github.event.pull_request.base.sha }}" \
              --until-commit "${{ github.event.pull_request.head.sha }}" \
              file:///repo
