name: PR Secret Scan (TruffleHog)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # need full history for scanning

      - name: Run TruffleHog scan on PR commits
        uses: docker://trufflesecurity/trufflehog:latest
        with:
          args: git --only-verified --fail --since-commit ${{ github.event.pull_request.base.sha }} file://.
